'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const R = require('./manual-zone-reassessment.js');
const aggressive = { zoneLow: 241.45, zoneHigh: 245.90 };
const conservative = { zoneLow: 237.05, zoneHigh: 241.50 };
let zone = R.suggestedZone(aggressive, conservative, 0.05);
assert.deepEqual([zone.low, zone.high, zone.status], [241.45, 241.5, 'ZONE_TOO_NARROW']);
zone = R.suggestedZone({ zoneLow: 240, zoneHigh: 245 }, { zoneLow: 235, zoneHigh: 240.15 }, 0.05);
assert.equal(zone.status, 'VALID');
assert.equal(R.suggestedZone({ zoneLow: 241.5 }, { zoneHigh: 241.45 }, 0.05).status, 'INVALID_SUGGESTED_ZONE');
let state = R.normalize();
state = R.prefillDraft(state, zone);
assert.deepEqual(state.manualDraft, { low: 240, high: 240.15, edited: false, editedAt: null, suggestedForDate: null, editedForDate: null });
state = R.setDraft(state, 239.8, 240.4);
state = R.prefillDraft(state, R.suggestedZone({ zoneLow: 241 }, { zoneHigh: 242 }, 0.05));
assert.equal(state.manualDraft.edited, true);
assert.equal(state.manualDraft.low, 239.8);
assert.equal(state.manualDraft.high, 240.4);
let applied = R.applyManualZone(state, undefined, undefined, '2026-08-18T00:00:00.000Z');
assert.equal(applied.applied, true);
assert.deepEqual(applied.state.activeManualZone, { low: 239.8, high: 240.4 });
assert.equal(applied.state.manualZoneSource, 'MANUAL');
assert.deepEqual(R.explicitActiveManualZone(applied.state), { low: 239.8, high: 240.4, manualAppliedAt: applied.state.manualAppliedAt });
assert.equal(R.explicitActiveManualZone({ activeManualZone: { low: 239.8, high: 240.4 }, manualZoneSource: 'MANUAL' }), null, 'a missing applied timestamp is not an explicit Manual Reassessment Active Zone');
assert.equal(R.explicitActiveManualZone({ activeManualZone: { low: 239.8, high: 240.4 }, manualZoneSource: 'MANUAL', manualAppliedAt: 'not-a-date' }), null, 'an invalid applied timestamp is not an explicit Manual Reassessment Active Zone');
assert.equal(applied.state.manualDraft.edited, false, 'applying separates the Active Manual Zone from the next editable draft');
state = R.prefillDraft(applied.state, R.suggestedZone({ zoneLow: 242 }, { zoneHigh: 243 }, 0.05));
assert.deepEqual(state.manualDraft, { low: 242, high: 243, edited: false, editedAt: null, suggestedForDate: null, editedForDate: null }, 'an unapplied draft follows the latest Suggested Zone after Apply Manual');
assert.deepEqual(state.activeManualZone, { low: 239.8, high: 240.4 }, 'a later Suggested Zone does not alter the applied Active Manual Zone');
const invalidSuggestedZone = R.suggestedZone({ zoneLow: 241.5 }, { zoneHigh: 241.45 }, 0.05);
assert.equal(invalidSuggestedZone.status, 'INVALID_SUGGESTED_ZONE');
applied = R.applyManualZone(R.setDraft(R.normalize(), 241.5, 242), undefined, undefined, undefined, invalidSuggestedZone);
assert.equal(applied.applied, true, 'an invalid Suggested Zone does not block a valid Manual Zone');
assert.deepEqual(applied.state.activeManualZone, { low: 241.5, high: 242 });
assert.equal(R.manualZoneIsValid(241.5, 242, invalidSuggestedZone.tickSize), true, 'Manual Zone accepts valid tick-aligned endpoints');
assert.equal(R.manualZoneIsValid(241.52, 242, invalidSuggestedZone.tickSize), false, 'Manual Zone rejects a non-tick-aligned endpoint');
const decimalDraft = R.setDraft(R.normalize(), '230.80', '233.35', '2026-08-19T01:00:00.000Z', '2026-08-19');
assert.deepEqual([decimalDraft.manualDraft.low, decimalDraft.manualDraft.high], [230.8, 233.35], 'Manual Draft accepts decimal ETF prices without coercing them to 0 or a single digit');
assert.deepEqual([R.normalize({ manualDraft: { low: '', high: '' } }).manualDraft.low, R.normalize({ manualDraft: { low: '', high: '' } }).manualDraft.high], [null, null], 'clearing a Manual Price does not coerce it to zero');
const yesterdayDraft = R.setDraft(R.normalize(), 237.60, 237.75, '2026-08-18T00:00:00.000Z', '2026-08-18');
const todaySuggestedZone = R.suggestedZone({ zoneLow: 240.00 }, { zoneHigh: 240.50 }, 0.05);
state = R.prefillDraft(yesterdayDraft, todaySuggestedZone, '2026-08-19');
assert.deepEqual(state.manualDraft, { low: 240, high: 240.5, edited: false, editedAt: null, suggestedForDate: '2026-08-19', editedForDate: null }, 'a new market day replaces a stale draft with today’s Suggested Zone');
state = R.setDraft(state, 239.50, 240.00, '2026-08-19T01:00:00.000Z', '2026-08-19');
assert.deepEqual(R.prefillDraft(state, todaySuggestedZone, '2026-08-19').manualDraft, state.manualDraft, 'a current-day user edit is preserved');
state = R.prefillDraft(yesterdayDraft, invalidSuggestedZone, '2026-08-19');
assert.deepEqual(state.manualDraft, { low: null, high: null, edited: false, editedAt: null, suggestedForDate: '2026-08-19', editedForDate: null }, 'an invalid Suggested Zone clears stale draft values instead of presenting a reversed recommendation');
const entryWatchHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
assert.match(entryWatchHtml, /wc-manual-reassess-low[^\r\n]*onchange=/, 'Manual Lower commits after the mobile edit completes, not on every typed character');
assert.match(entryWatchHtml, /wc-manual-reassess-high[^\r\n]*onchange=/, 'Manual Upper commits after the mobile edit completes, not on every typed character');
assert.doesNotMatch(entryWatchHtml, /wc-manual-reassess-(?:low|high)[^\r\n]*oninput=/, 'Manual decimal typing does not trigger a panel rerender per character');assert.match(entryWatchHtml, /const suggestedLabel = \['VALID', 'ZONE_TOO_NARROW'\]\.includes\(zone\.status\)/, 'Entry Watch displays a Suggested Zone only when its endpoints are valid');
assert.match(entryWatchHtml, /Suggested Zone is invalid\. Enter a Manual Price range to continue\./, 'Entry Watch labels invalid Suggested Zones as manual-input-required');
assert.doesNotMatch(entryWatchHtml, /state\.manualDraft\.low[^\n]*\$\{actionable \? '' : 'disabled'\}/, 'Manual number inputs stay editable on mobile');
assert.match(entryWatchHtml, /const applyDisabled = !actionable \|\| !helper\.manualZoneIsValid\(state\.manualDraft\.low, state\.manualDraft\.high, zone\.tickSize\);/, 'Apply Manual is gated by the entered Manual Zone, not Suggested Zone validity');
assert.match(entryWatchHtml, /currentMarketDate !== previousMarketDate/, 'a newly observed market day recalculates the existing Suggested Zones');
const legacyAppliedState = {
  manualDraft: { low: 237.05, high: 237.85, edited: true },
  activeManualZone: { low: 237.05, high: 237.85 },
  manualZoneSource: 'MANUAL',
  manualAppliedAt: '2026-08-17T00:00:00.000Z'
};
state = R.migrateLegacyAppliedDraft(legacyAppliedState);
state = R.prefillDraft(state, R.suggestedZone({ zoneLow: 237.60 }, { zoneHigh: 237.75 }, 0.05));
assert.deepEqual(state.manualDraft, { low: 237.60, high: 237.75, edited: false, editedAt: null, suggestedForDate: null, editedForDate: null }, 'legacy Apply-only draft flag migrates to the latest Suggested Zone');
assert.deepEqual(state.activeManualZone, { low: 237.05, high: 237.85 }, 'legacy migration never changes the Active Manual Zone');
const genuineDraft = R.setDraft(legacyAppliedState, 237.1, 237.9, '2026-08-18T00:00:00.000Z');
assert.equal(R.migrateLegacyAppliedDraft(genuineDraft).manualDraft.edited, true, 'a current user-edited draft is not migrated');
state = R.evaluateDaily(R.normalize(), { timeframe: 'daily', period: '2026-08-10', close: 241, zone }).state;
assert.equal(state.counter, 0, 'first completed candle starts a baseline only');
state = R.evaluateDaily(state, { timeframe: 'daily', period: '2026-08-11', close: 241, zone }).state;
assert.equal(state.counter, 1);
const changedZone = R.suggestedZone({ zoneLow: 242, zoneHigh: 245 }, { zoneLow: 238, zoneHigh: 242.1 }, 0.05);
state = R.evaluateDaily(state, { timeframe: 'daily', period: '2026-08-12', close: 243, zone: changedZone }).state;
assert.equal(state.counter, 2, 'each completed close uses that day’s suggested zone');
state = R.evaluateDaily(state, { timeframe: 'daily', period: '2026-08-13', close: 242.05, zone: changedZone }).state;
assert.equal(state.counter, 0, 'inside today’s zone resets');
state = R.evaluateDaily(state, { timeframe: 'daily', period: '2026-08-14', close: 240, zone: changedZone }).state;
assert.equal(state.counter, 0, 'below today’s zone resets');
assert.equal(R.evaluateDaily(state, { timeframe: 'daily', period: '2026-08-14', close: 250, zone: changedZone }).evaluated, false, 'period is counted only once');
assert.equal(R.evaluateDaily(state, { timeframe: 'weekly', period: '2026-W33', close: 250, zone: changedZone }).active, false, 'weekly counting is inactive');
state = R.startSequence({ ...state, snapshots: [{ tradingDate: 'old' }], counter: 2 }, 'weekly');
assert.deepEqual([state.counter, state.snapshots.length], [0, 0], 'timeframe change clears only the reassessment sequence');
state = R.setThreshold(state, 2);
assert.equal(state.threshold, 2);
assert.equal(R.resetCounter({ ...state, counter: 2 }).counter, 0);
console.log('Manual reassessment tests passed.');
